export { FriendCreateArgs } from './friend-create.args';
export { FriendCreateInput } from './friend-create.input';
export { FriendEditArgs } from './friend-edit.args';
export { FriendEditInput } from './friend-edit.input';
export { FriendFindManyWhereInput } from './friend-find-many-where.input';
export { FriendFindManyArgs } from './friend-find-many.args';
export { FriendRemoveArgs } from './friend-remove.args';
export { FriendWhereUniqueInput } from './friend-where-unique.input';
export { Friend } from './friend.model';
