version: '3.7'
services:
  birthdayapp_development_postgres_user:
    container_name: 'birthdayapp_development_postgres_user'
    image: 'postgres'
    restart: always
    env_file:
      - ./apps/user/.env
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - /home/birthdayapp_development_postgres_user/docker_data/db-data/development:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - birthdayapp_development_postgres_user

  birthdayapp_development_postgres_friend:
    container_name: 'birthdayapp_development_postgres_friend'
    image: 'postgres'
    restart: always
    env_file:
      - ./apps/friends/.env
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - /home/birthdayapp_development_postgres_friend/docker_data/db-data/development:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - birthdayapp_development_postgres_friend

  birthdayapp_development_user:
    env_file:
      - ./apps/user/.env
    container_name: birthdayapp_development_user
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.user
      args:
        TAGS: master
    ports:
      - '9100:9100'
    depends_on:
      - birthdayapp_development_postgres_user

  birthdayapp_development_friends:
    env_file:
      - ./apps/friends/.env
    container_name: birthdayapp_development_friends
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.friends
      args:
        TAGS: master
    ports:
      - '9101:9101'
    depends_on:
      - birthdayapp_development_postgres_friend

  birthdayapp_development_gateway:
    env_file:
      - ./apps/gateway/.env
    container_name: birthdayapp_development_gateway
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.gateway
      args:
        TAGS: master
    ports:
      - '9102:9102'

networks:
  birthdayapp_development_postgres_user:
    driver: bridge
  birthdayapp_development_postgres_friend:
    driver: bridge
