version: '3.7'
services:
  birthdayapp_development_postgres:
    container_name: birthdayapp_development_postgres
    image: postgres
    restart: always
    env_file:
      - .development.env
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - /home/birthdayapp_development_postgres/docker_data/db-data/development:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  birthdayapp_development_migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - birthdayapp_development_postgres
    links:
      - birthdayapp_development_postgres

  birthdayapp_development_gateway:
    env_file:
      - .development.env
    image: birthdayapp_development_gateway
    restart: always
    ports:
      - '127.0.0.1:${GATEWAY_PORT}:${GATEWAY_PORT}'
    depends_on:
      - birthdayapp_development_postgres
    links:
      - birthdayapp_development_postgres
