version: '3.7'
services:
  birthdayapp_development_postgres_user:
    container_name: 'birthdayapp_development_postgres_user'
    image: 'postgres'
    restart: always
    env_file:
      - .development.env
    ports:
      - '${USER_DATABASE_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${USER_DATABASE_PASSWORD}
      POSTGRES_USER: ${USER_DATABASE_USERNAME}
      POSTGRES_DB: ${USER_DATABASE_NAME}
    volumes:
      - /home/birthdayapp_development_postgres_user/docker_data/db-data/development:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  birthdayapp_development_postgres_friend:
    container_name: 'birthdayapp_development_postgres_friend'
    image: 'postgres'
    restart: always
    env_file:
      - .development.env
    ports:
      - '${FRIEND_DATABASE_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${FRIEND_DATABASE_PASSWORD}
      POSTGRES_USER: ${FRIEND_DATABASE_USERNAME}
      POSTGRES_DB: ${FRIEND_DATABASE_NAME}
    volumes:
      - /home/birthdayapp_development_postgres_friend/docker_data/db-data/development:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  birthdayapp_development_postgres_note:
    container_name: 'birthdayapp_development_postgres_note'
    image: 'postgres'
    restart: always
    env_file:
      - .development.env
    ports:
      - '${NOTE_DATABASE_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${NOTE_DATABASE_PASSWORD}
      POSTGRES_USER: ${NOTE_DATABASE_USERNAME}
      POSTGRES_DB: ${NOTE_DATABASE_NAME}
    volumes:
      - /home/birthdayapp_development_postgres_note/docker_data/db-data/development:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  birthdayapp_development_user:
    env_file:
      - .development.env
    environment:
      DATABASE_URL: ${USER_DATABASE_URL}
    image: birthdayapp_development_user
    restart: always
    ports:
      - '127.0.0.1:${USER_PORT}:${USER_PORT}'
    links:
      - birthdayapp_development_postgres_user

  birthdayapp_development_friend:
    env_file:
      - .development.env
    environment:
      DATABASE_URL: ${FRIEND_DATABASE_URL}
    image: birthdayapp_development_friend
    restart: always
    ports:
      - '127.0.0.1:${FRIEND_PORT}:${FRIEND_PORT}'
    links:
      - birthdayapp_development_postgres_friend

  birthdayapp_development_note:
    env_file:
      - .development.env
    environment:
      DATABASE_URL: ${NOTE_DATABASE_URL}
    image: birthdayapp_development_note
    restart: always
    ports:
      - '127.0.0.1:${NOTE_PORT}:${NOTE_PORT}'
    links:
      - birthdayapp_development_postgres_note

  birthdayapp_development_gateway:
    env_file:
      - .development.env
    image: birthdayapp_development_gateway
    restart: always
    ports:
      - '127.0.0.1:${GATEWAY_PORT}:${GATEWAY_PORT}'
